version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    links:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - "1433:1433"
